language: rust
sudo: required
dist: trusty
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chown root:wheel /usr/local/bin/brew ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc libegl1-mesa-dev libgles2-mesa-dev ; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"         ; fi
  # TODO: test wasm
  #- rustup target add wasm32-unknown-unknown
  #- cargo install wasm-bindgen-cli
  #- travis_wait 120 wasm-pack build
  - travis_wait 30 cargo build --verbose
  - cargo test --verbose
os:
  - linux
  - osx
