language: rust
sudo: required
dist: trusty
rust:
  - nightly
  - beta
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chown root:wheel /usr/local/bin/brew ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link sdl2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev gcc libegl1-mesa-dev libgles2-mesa-dev ; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"         ; fi
  - cargo build --verbose
  - cargo test --verbose
os:
  - linux
  - osx
