version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
skip_branch_with_pr: true
branches:
    only:
        - updates
platform:
  - x64
build_script:
- cmd: >-
    echo on

    echo AddMessage "PLATFORM is %PLATFORM%"

    if "%PLATFORM%" == "x86" set RUST_INSTALL=i686-pc-windows-msvc

    if "%PLATFORM%" == "x64" set RUST_INSTALL=x86_64-pc-windows-msvc

    echo AddMessage "platform is %platform%"

    appveyor AddMessage "Platform rust: %RUST_INSTALL%"

    appveyor DownloadFile "https://static.rust-lang.org/dist/rust-nightly-%RUST_INSTALL%.exe" -FileName rust-install.exe

    "./rust-install.exe" /VERYSILENT /NORESTART /DIR="C:\Rust\"

    SET PATH=%PATH%;C:\Rust\bin

    rustc -V

    cargo -V

    cargo build

    mkdir dist-debug

    cp target\debug\steven.exe dist-debug



    cargo build --release

    mkdir dist

    cp target\release\steven.exe dist


artifacts:
- path: dist
- path: dist-debug
