[package]
name = "steven_blocks"
version = "0.0.1"
authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>" ]

[dependencies]
lazy_static = "1.1.0"
cgmath = "0.16.1"
collision = "0.18.0"


[dependencies.steven_shared]
path = "../shared"
version = "0"
